CREATE DATABASE IF NOT EXISTS `itc127-cs2a-2026`;
CREATE USER IF NOT EXISTS 'mark'@'localhost' IDENTIFIED BY 'acobado';
GRANT ALL PRIVILEGES ON `itc127-cs2a-2026`.* TO 'mark'@'localhost';
FLUSH PRIVILEGES;
